POST http://localhost:8080/category HTTP/1.1
Host: localhost:8080
Content-Type: application/json

{
  "name": "Category 2",
  "description": "Category 2 description"
}

###

GET http://localhost:8080/category/008504a9-031c-45d3-b645-6e960921c385 HTTP/1.1
Content-Type: application/json

###

GET http://localhost:8080/category HTTP/1.1
Content-Type: application/json

###

POST http://localhost:8080/product HTTP/1.1
Content-Type: application/json

{
  "name": "Product 2",
  "description": "Product 2 description",
  "price": 100.20,
  "image_url": "http://google.com",
  "category_id":"008504a9-031c-45d3-b645-6e960921c385"
}

###

GET http://localhost:8080/product HTTP/1.1
Content-Type: application/json