version: '3'
services:
  db:
    image: mysql:8.0.30-debian
    ports:
      - 3305:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nest
      MYSQL_USER: orders
      MYSQL_PASSWORD: root

  rabbitmq:
    image: rabbitmq:3.12-management
    ports:
      - 15673:15672
      - 5672:5672
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin